force-app/main/default/objects/public_serviceattribute__x/public_serviceattribute__x.object-meta.xml
<CustomObject>
    <description>public$serviceattribute</description>
    <externalDataSource>Remote_Compute_Results</externalDataSource>
    <externalName>public$serviceattribute</externalName>
    <label>Remote Service Attribute</label>
    <pluralLabel>Remote Service Attributes</pluralLabel>
</CustomObject>

force-app/main/default/objects/public_serviceattribute__x/fields/attributeallowedvalues__c.field-meta.xml
<CustomField>
    <fullName>attributeallowedvalues__c</fullName>
    <description>attributeallowedvalues</description>
    <externalDeveloperName>attributeallowedvalues</externalDeveloperName>
    <label>Attribute Allowed Values</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/public_serviceattribute__x/fields/attributedescription__c.field-meta.xml
<CustomField>
    <fullName>attributedescription__c</fullName>
    <description>attributedescription</description>
    <externalDeveloperName>attributedescription</externalDeveloperName>
    <label>Attribute Description</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/public_serviceattribute__x/fields/attributelabel__c.field-meta.xml
<CustomField>
    <fullName>attributelabel__c</fullName>
    <description>attributelabel</description>
    <externalDeveloperName>attributelabel</externalDeveloperName>
    <label>Attribute Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/public_serviceattribute__x/fields/attributename__c.field-meta.xml
<CustomField>
    <fullName>attributename__c</fullName>
    <description>attributename</description>
    <externalDeveloperName>attributename</externalDeveloperName>
    <label>Attribute Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/public_serviceattribute__x/fields/refservicedefinitionid__c.field-meta.xml
<CustomField>
    <fullName>refservicedefinitionid__c</fullName>
    <description>refservicedefinitionid</description>
    <externalDeveloperName>refservicedefinitionid</externalDeveloperName>
    <label>refservicedefinitionid</label>
    <length>255</length>
    <referenceTo>public_servicedefinition__x</referenceTo>
    <relationshipLabel>public$serviceattribute</relationshipLabel>
    <relationshipName>public_serviceattribute</relationshipName>
    <type>ExternalLookup</type>
</CustomField>

force-app/main/default/classes/ServiceAttributeControler.cls
public with sharing class ServiceAttributeControler {

    @AuraEnabled(cacheable=True)
    public static List<public_serviceattribute__x> getServiceAttributes(String serviceId){
        return [ select id__c, 
            attributedescription__c, 
            attributelabel__c,
            attributename__c,
            attributeallowedvalues__c
            from  
            public_serviceattribute__x 
            where refservicedefinitionid__c = :serviceId ];
    }
}